<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Service\Banco'                          => __DIR__ . '/Banco/Service.php',
  'Service\Entity'                         => __DIR__ . '/EntityService.php',
);
