<h1>Regiones</h1>
<?php if($this->mapa==1):?>
<div style="position:relative;display:block;width:500px;height:500px;">
 <img src="/images/mapa.bmp" width="500px" height="500px"/>
 <span style="position:absolute;left:100;top:443;color:black;font-size:15px;font-weight:bold"><a style="text-decoration:none" href="/regiones/ver/info/14">KameHouse</a></span>
 <span style="position:absolute;left:250;top:250;color:black;font-size:15px;font-weight:bold"><a style="text-decoration:none" href="/regiones/ver/info/3">Tokyo-3</a></span>
 <span style="position:absolute;left:195;top:290;color:black;font-size:15px;font-weight:bold"><a style="text-decoration:none" href="/regiones/ver/info/4">Tomoeda</a></span>
 <span style="position:absolute;left:425;top:159;color:black;font-size:15px;font-weight:bold"><a style="text-decoration:none" href="/regiones/ver/info/11">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aldea<br>Oculta de<br>&nbsp;&nbsp;&nbsp;Konoha</a></span>
 <span style="position:absolute;left:415;top:246;color:black;font-size:15px;font-weight:bold"><a style="text-decoration:none" href="/regiones/ver/info/12">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aldea<br>Oculta de<br>&nbsp;&nbsp;&nbsp;la Arena</a></span>
 <span style="position:absolute;left:135;top:10;color:black;font-size:15px;font-weight:bold"><a style="text-decoration:none" href="/regiones/ver/info/7">Monte Plateado</a></span>
 <span style="position:absolute;left:50;top:50;color:black;font-size:15px;font-weight:bold"><a style="text-decoration:none" href="/regiones/ver/info/6">Ciudad Azafr&aacute;n</a></span>
 <span style="position:absolute;left:247;top:70;color:black;font-size:15px;font-weight:bold"><a style="text-decoration:none" href="/regiones/ver/info/8">Dalmasca</a></span>
 <span style="position:absolute;left:108;top:166;color:black;font-size:15px;font-weight:bold"><a style="text-decoration:none" href="/regiones/ver/info/10">Balamb</a></span>
 <span style="position:absolute;left:15;top:180;color:black;font-size:15px;font-weight:bold"><a style="text-decoration:none" href="/regiones/ver/info/13">N<br>a<br>m<br>e<br>k<br>k<br>u<br>s<br>e<br>i</a></span>
 <span style="position:absolute;left:280;top:320;color:black;font-size:15px;font-weight:bold"><a style="text-decoration:none" href="/regiones/ver/info/5">Aldea<br>Yokomon</a></span>
</div>
<?php else: ?>
<h2><?php echo $this->nombre ?></h2>
<div class="r-imagen"><?php echo $this->imagen ?></div>
<div class="r-desc"><?php echo $this->descripcion ?></div>

    <?php if($this->canth > 0): ?>
<hr><hr><h3>Sectores</h3>
<?php foreach($this->hijos as $h): ?>
<div class="r-h"><hr>
<h4><?php echo $h['nombre'] ?></h4>
<div class="r-imagen"><?php echo $h['imagen'] ?></div>
<div class="r-desc"><?php echo $h['descripcion'] ?></div>
<div class="r-accion redondo"><?php echo $h['accion'] ?></div>
</div>
<?php endforeach ?>
    <?php else: ?>
    
    <div class="r-accion redondo"><?php echo $this->accion ?></div>

    <?php endif ?>

<?php endif ?>