<?php
// layout.phtml
// First get the viewmodel and all its children (ie the actions viewmodel)
$children = $this->viewModel()
                 ->getCurrent()
                 ->getChildren();

$ourView  = $children[0];
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">  
<html>  
    <head>  
        <title><?php echo $this->title; ?></title>  
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">  
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/jquery.cleditor.css')  
			->prependStylesheet($this->basePath() . '/css/jquery.alerts.css')  
                        ->prependStylesheet($this->basePath() . '/css/estilos.css')  
			->prependStylesheet($this->basePath() . '/css/960.css')
			->prependStylesheet($this->basePath() . '/css/text.css')
			->prependStylesheet($this->basePath() . '/css/reset.css') ?>
<script type="text/javascript" src="/javascript/jquery.min.js"></script>
<script type="text/javascript" src="/javascript/jquery.corner.js"></script>
<script type="text/javascript" src="/javascript/jquery.utils.js"></script>
<script type="text/javascript" src="/javascript/jquery.ui.draggable.js"></script>
<script type="text/javascript" src="/javascript/jquery.alerts.js"></script>
<script type="text/javascript" src="/javascript/jquery.cleditor.min.js"></script>                                      
<script type="text/javascript">
$(document).ready(function(){
  $(".redondo").corner();
});
</script>   

    </head>  
    <body>  

        <div class="container_16">
           <div class="grid_16">
                <a href="/"><img src="<?php echo $this->baseUrl; ?>/images/logo.gif" /></a>
            </div>
            <div class="clear"></div>
            
           <div class="grid_16" id="sep"></div>
            <div class="clear"></div>

            <div class="grid_3" id="izq">
                <div class="alpha omega grid_3" id="nav_izq_cab"></div>
                <div class="clear"></div>                           
                <div class="alpha omega grid_3" id="nav_izq_con">
                    <div class="alpha omega grid_3" id="nav_izq_sec"></div>
                    <div class="clear"></div>    
                    <div class="grid_3" id="nav_izq_enl">
                        <br />
                        <a href="#" id="enl_inicio"><span>Inicio</span></a><br />
                        <a href="/noticias/index" id="enl_noticias"><span>Noticias</span></a><br />                        
                        <a href="#" id="enl_foros"><span>Foros</span></a><br /> <br />
                        
                        <a href="#" id="enl_tamagochi"><span>Tamagochi</span></a><br /><br />
                        
                        <a href="#" id="enl_enciclopedia"><span>Enciclopedia</span></a><br />
                        <a href="#" id="enl_imagenes"><span>Imagenes</span></a><br />                        
                        <a href="#" id="enl_descargas"><span>Descargas</span></a><br /><br />
                        
                        <a href="#" id="enl_contacto"><span>Contacto</span></a><br />                        
                    </div>
                    <div class="clear"></div>    
                </div>
                <div class="clear"></div>                                           
                <div class="alpha omega grid_3" id="nav_izq_fot"></div>
                <div class="clear"></div>                           
            </div>    
            <div class="grid_10" id="cont">
                <div class="alpha omega grid_10" id="cont_cab"></div>
                <div class="clear"></div>                           
                <div class="alpha omega grid_10" id="cont_con">
                    <div class="grid_10" id="cont_int_cab"></div>
                    <div class="clear"></div>                           
                    <div class="grid_10" id="cont_int_con">
                        <div class="grid_9" id="cont_cont">
                        <?php
                        if (isset($ourView->messages) && count($ourView->messages)) : ?>
                        
                        <script>jAlert('<?php foreach ($ourView->messages as $fMessage) : ?><?php echo $fMessage; ?><?php endforeach; ?>', '');</script>

                        <?php endif; ?>
                            <?php echo $this->content; ?>  
                        </div>    
                    </div>
                    <div class="clear"></div>                                           
                    <div class="grid_10" id="cont_int_fot"></div>
                    <div class="clear"></div>                                             
                </div>
                <div class="clear"></div>                                           
                <div class="alpha omega grid_10" id="cont_fot"></div>
                <div class="clear"></div>                           
                
            </div>    
            <div class="grid_3" id="der">
                <div class="alpha omega grid_3" id="nav_der_cab"></div>
                <div class="clear"></div>                           
                <div class="alpha omega grid_3" id="nav_der_con">
                    <p style="color: red"><br/><br/><br/>BARRA DE NAVEGACION DERECHA<br/><br/><br/></p>
                </div>
                <div class="clear"></div>                                           
                <div class="alpha omega grid_3" id="nav_der_fot"></div>
                <div class="clear"></div>                                        
            </div>    
            <div class="clear"></div>            
        </div>    
    </body>  
</html> 
