<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Controller\ControllerBase'    => __DIR__ . '/ControllerBase.php',
  'Controller\ControllerPublic'  => __DIR__ . '/ControllerPublic.php',
  'Controller\ControllerAjax'    => __DIR__ . '/ControllerAjax.php',
  'Controller\ControllerPrivate' => __DIR__ . '/ControllerPrivate.php',
);
