<h1>Bancos</h1><br>
<?php if($this->lista==1):?>
<div class="listabancos">
<?php foreach($this->listab as $banco):?>
<div class="banco">
<h2><?php echo $banco->nombre ?></h2><br>
<?php echo $banco->descripcion ?><br><br>
Moneda: <?php //echo $banco->moneda ?> (<?php //echo $banco->simbolo ?>)
<?php if($banco->id != 1): ?>
<br><br>Tipo de cambio (promedio): <?php //echo $banco->tipo_cambio." ".$banco->simbolo." = 1 OD"?>
<?php endif ?>
</div>
<div class="r-accion redondo"><a href="/banco/ver/info/<?php echo $banco->id ?>">Ver sucursales</a></div>
<br>
<?php endforeach ?>
</div>
<?php else: ?>
<h2><?php echo $banco->nombre ?></h2><br>
<?php echo $banco->descripcion ?><br><br>
Moneda: <?php echo $banco->moneda ?> (<?php echo $banco->simbolo ?>)
<?php if($banco->id != 1): ?>
<br><br>Tipo de cambio (promedio): <?php echo $banco->tipo_cambio." ".$banco->simbolo." = 1 OD"?>
<?php endif ?>


<?php endif ?>